//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnsureFramework.Assertions.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EnsureFramework.Assertions.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All items do not match the predicate..
        /// </summary>
        internal static string All_items_do_not_match_the_predicate {
            get {
                return ResourceManager.GetString("All_items_do_not_match_the_predicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item is not in enumerable..
        /// </summary>
        internal static string Item_is_not_in_enumerable {
            get {
                return ResourceManager.GetString("Item_is_not_in_enumerable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items..
        /// </summary>
        internal static string No_items {
            get {
                return ResourceManager.GetString("No_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items match the predicate..
        /// </summary>
        internal static string No_items_match_the_predicate {
            get {
                return ResourceManager.GetString("No_items_match_the_predicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection does not contain the value..
        /// </summary>
        internal static string Not_contains {
            get {
                return ResourceManager.GetString("Not_contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key &apos;{0}&apos; is not in the dictionary..
        /// </summary>
        internal static string The_key_keyName_is_not_in_the_dictionary_Format {
            get {
                return ResourceManager.GetString("The_key_keyName_is_not_in_the_dictionary_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string does not match the regular expression &apos;{0}&apos;..
        /// </summary>
        internal static string The_string_does_not_match_the_regex_Format {
            get {
                return ResourceManager.GetString("The_string_does_not_match_the_regex_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string is empty..
        /// </summary>
        internal static string The_string_is_empty {
            get {
                return ResourceManager.GetString("The_string_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string is whitespace..
        /// </summary>
        internal static string The_string_is_whitespace {
            get {
                return ResourceManager.GetString("The_string_is_whitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is a negative number..
        /// </summary>
        internal static string The_value_is_a_negative_number {
            get {
                return ResourceManager.GetString("The_value_is_a_negative_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is equal to zero..
        /// </summary>
        internal static string The_value_is_equal_to_zero {
            get {
                return ResourceManager.GetString("The_value_is_equal_to_zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is not a valid GUID..
        /// </summary>
        internal static string The_value_is_not_a_vaild_guid {
            get {
                return ResourceManager.GetString("The_value_is_not_a_vaild_guid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is not equal to &apos;{0}&apos;..
        /// </summary>
        internal static string The_value_is_not_equal_to_value_Format {
            get {
                return ResourceManager.GetString("The_value_is_not_equal_to_value_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is not greater than or equal to &apos;{0}&apos;..
        /// </summary>
        internal static string The_value_is_not_greater_than_or_equal_to_value_Format {
            get {
                return ResourceManager.GetString("The_value_is_not_greater_than_or_equal_to_value_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is not greater than &apos;{0}&apos;..
        /// </summary>
        internal static string The_value_is_not_greater_than_value_Format {
            get {
                return ResourceManager.GetString("The_value_is_not_greater_than_value_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is not less than or equal to &apos;{0}&apos;..
        /// </summary>
        internal static string The_value_is_not_less_than_or_equal_to_value_Format {
            get {
                return ResourceManager.GetString("The_value_is_not_less_than_or_equal_to_value_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is not less than &apos;{0}&apos;..
        /// </summary>
        internal static string The_value_is_not_less_than_value_Format {
            get {
                return ResourceManager.GetString("The_value_is_not_less_than_value_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is not within and including the range &apos;{0}-{1}&apos;..
        /// </summary>
        internal static string The_value_is_not_within_and_including_the_range_lowerBound_to_upperBound_Format {
            get {
                return ResourceManager.GetString("The_value_is_not_within_and_including_the_range_lowerBound_to_upperBound_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is not within the range &apos;{0}-{1}&apos;..
        /// </summary>
        internal static string The_value_is_not_within_the_range_lowerBound_to_upperBound_Format {
            get {
                return ResourceManager.GetString("The_value_is_not_within_the range_lowerBound_to_upperBound_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be of type &apos;{0}&apos;..
        /// </summary>
        internal static string The_value_must_be_of_type_typeName_Format {
            get {
                return ResourceManager.GetString("The_value_must_be_of_type_typeName_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be one of (&apos;{0}&apos;)..
        /// </summary>
        internal static string The_value_must_be_one_of_valueList_Format {
            get {
                return ResourceManager.GetString("The_value_must_be_one_of_valueList_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must inherit from type &apos;{0}&apos;..
        /// </summary>
        internal static string The_value_must_inherit_from_type_typeName_Format {
            get {
                return ResourceManager.GetString("The_value_must_inherit_from_type_typeName_Format", resourceCulture);
            }
        }
    }
}
