<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>EnsureFramework</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EnsureFramework.Assertions\EnsureFramework.Assertions.csproj" />
  </ItemGroup>

</Project>
