<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Authors>Michael Coxon</Authors>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <Description>EnsureFramework is designed to take the pain out of null checking and making sure (ensuring) your methods are being used the way they were intended and throwing exceptions when unsupported values are passed to them.

You can make sure values are in a specific range or simply make sure that an argument is not null.

It was designed to be readable and fluent based, meaning you can chain ensurables together and the first one that fails will result in the exception.</Description>
    <Copyright>Copyright 2018-2026</Copyright>
    <PackageProjectUrl>https://github.com/michaelcoxon/EnsureFramework</PackageProjectUrl>
    <RepositoryUrl>https://github.com/michaelcoxon/EnsureFramework</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>runtime-contracts,ensure,contracts</PackageTags>
    <NeutralLanguage>en</NeutralLanguage>
    <Version>2.0.3-alpha</Version>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <CodeAnalysisRuleSet>../EnsureFramework.ruleset</CodeAnalysisRuleSet>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
    <None Include="..\LICENSE" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EnsureFramework.Ensure\EnsureFramework.Ensure.csproj" />
    <ProjectReference Include="..\EnsureFramework.Validate\EnsureFramework.Validate.csproj" />
  </ItemGroup>

</Project>
