//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnsureFramework.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EnsureFramework.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All items do not match the predicate..
        /// </summary>
        internal static string All_items_do_not_match_the_predicate {
            get {
                return ResourceManager.GetString("All_items_do_not_match_the_predicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}[\&quot;{1}\&quot;] is not in the dictionary..
        /// </summary>
        internal static string Dictionary_argName_with_key_keyName_is_not_in_the_dictionary_Format {
            get {
                return ResourceManager.GetString("Dictionary_argName_with_key_keyName_is_not_in_the_dictionary_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item is not in enumerable..
        /// </summary>
        internal static string Item_is_not_in_enumerable {
            get {
                return ResourceManager.GetString("Item_is_not_in_enumerable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items..
        /// </summary>
        internal static string No_items {
            get {
                return ResourceManager.GetString("No_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items match the predicate..
        /// </summary>
        internal static string No_items_match_the_predicate {
            get {
                return ResourceManager.GetString("No_items_match_the_predicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &apos;{0}&apos; is not equal to &apos;{1}&apos;..
        /// </summary>
        internal static string The_argument_argName_is_not_equal_to_value_Format {
            get {
                return ResourceManager.GetString("The_argument_argName_is_not_equal_to_value_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &apos;{0}&apos; is not greater than or equal to &apos;{1}&apos;..
        /// </summary>
        internal static string The_argument_argName_is_not_greater_than_or_equal_to_value_Format {
            get {
                return ResourceManager.GetString("The_argument_argName_is_not_greater_than_or_equal_to_value_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &apos;{0}&apos; is not greater than &apos;{1}&apos;..
        /// </summary>
        internal static string The_argument_argName_is_not_greater_than_value_Format {
            get {
                return ResourceManager.GetString("The_argument_argName_is_not_greater_than_value_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &apos;{0}&apos; is not less than &apos;{1}&apos;..
        /// </summary>
        internal static string The_argument_argName_is_not_less_than_value_Format {
            get {
                return ResourceManager.GetString("The_argument_argName_is_not_less_than_value_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &apos;{0}&apos; is not within and including the range &apos;{1}-{2}&apos;..
        /// </summary>
        internal static string The_argument_argName_is_not_within_and_including_the_range_lowerBound_to_upperBound_Format {
            get {
                return ResourceManager.GetString("The_argument_argName_is_not_within_and_including_the_range_lowerBound_to_upperBou" +
                        "nd_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &apos;{0}&apos; is not within the range &apos;{1}-{2}&apos;..
        /// </summary>
        internal static string The_argument_argName_is_not_within_the_range_lowerBound_to_upperBound_Format {
            get {
                return ResourceManager.GetString("The_argument_argName_is_not_within_the range_lowerBound_to_upperBound_Format", resourceCulture);
            }
        }
    }
}
